resources:
  - name: node_app
    type: gitRepo
    repoPath: manishas/sample_node
    configuration:
      integrationName: manishas_github
      branches:
        only: master
    initialVersion:
      sha: master

pipelines:
  - name: node_ci_pipeline
    steps:
      - name: node_build_step
        type: bash
        setup:
          runtime: 
            type: image
            image:
              custom:
                name: drydock/u16all
                tag: master
        requires:
          integrations:
            - orbiteraArtifactory
        triggeredBy:
          resources:
            - node_app 
        execution:
          onExecute:
            - echo "executing test bash step..."
            - printenv
            - docker login -u $int_orbiteraArtifactory_username -p $int_orbiteraArtifactory_password $int_orbiteraArtifactory_url
            - rt_ip=$(echo $int_orbiteraArtifactory_url | awk -F[/:] '{print $4}')
            - rt_port=$(echo $int_orbiteraArtifactory_url | awk -F[/:] '{print $5}')
            - echo $rt_ip
            - echo $rt_port     
            - docker pull $rt_ip:$rt_port/docker-virtual/busybox:latest
            - ls $res_node_app_resourcePath/gitRepo
            - pushd $res_node_app_resourcePath/gitRepo
            - docker build -t $rt_ip:$rt_port/docker-virtual/alpine:$STEP_ID -f Dockerfile .
            - docker push $rt_ip:$rt_port/docker-virtual/alpine:$STEP_ID
